development:
  adapter: mysql2
  database: wechat_dev
  encoding: utf8
  username: root
  password: ''
  host: 127.0.0.1
  pool: 5
  timeout: 5000

test:
    adapter: mysql2
    encoding: utf8
    database: wechat_dev
    username: root
    password: "13636632007"
    host: 127.0.0.1
    pool: 5
    timeout: 5000

production:
    adapter: mysql2
    encoding: utf8
    reconnect: false
    database: wechat_dev
    pool: 5
    username: root
    password: '13636632007'